### ISSUE TITLE
Problem recovering symbols from binaries compiled with go1.20.2

### ISSUE THREAD

**Issue by martclau** [mandiant/GoReSym#17]
```
> GoReSym_win.exe x.exe
{"error": "Failed to parse file: failed to read pclntab: failed to locate pclntab"}

> go version x.exe
dosia_app_windows_x64.exe: go1.20.2
```

**Comment by stevemk14ebr** [comment]
I can successfully recover symbols from a freshly compiled and stripped Go 1.20.2 binary, please provide a binary to reproduce with.

**Comment by martclau** [comment]
It doesn't work for (as you can see, VT also has problems):

https://www.virustotal.com/gui/file/62fbacc70c7b00faaf1f5a0a77e414d404137f5a1ef2d23ed14382eed130795a

But works for (same program, just compiled for Linux):

https://www.virustotal.com/gui/file/eb8602a16232ab4821667b19e1354071946243437e1b9fddb4ebaa6250518eee

**Comment by stevemk14ebr** [comment]
thanks, I can reproduce this now. I am investigating and will update when I know the cause and have a fix identified.

**Comment by martclau** [comment]
Works now - thanks :-)
