### ISSUE TITLE
Error : Failed to parse file: failed to read pclntab: failed to locate pclntab

### ISSUE THREAD

**Issue by nateambringit** [mandiant/GoReSym#20]
Hi I trying to execute the prebuilt of GoReSym newest version 2.2 in windows and the feedback is this :
![image](https://user-images.githubusercontent.com/22272022/230768141-ba56bb98-da77-4f4f-9d0b-9b5ada7dc67b.png)

and it same as when i am building with go-1.20.

![image](https://user-images.githubusercontent.com/22272022/230768387-2843edc7-6b82-4aed-b136-e888f74a24f6.png)

How to fix this?

**Comment by williballenthin** [comment]
are you able to share the sample that leads to this error?

**Comment by nateambringit** [comment]
> are you able to share the sample that leads to this error?

Yes i used sample of malware : [https://mega.nz/file/r7RV1ZjC#WvrfdjEzpWq-4a6GS7FsbXr7g92KOHL2kL6XZXeSDMk](url) (Pass: infected) .

**Comment by stevemk14ebr** [comment]
Hi, your malware sample is packed or obfuscated. The NetSysCLI.exe is not a plain go binary
