### ISSUE TITLE
GoReSym binary is linked with libyara.so.10 on Linux

### ISSUE THREAD

**Issue by xusheng6** [mandiant/GoReSym#23]
When I tried to run it on Ubuntu 22.04, I get an error message that `libyara.so.10` is missing. I installed the `libyara-dev` with apt, but it did not fix the problem, since the one that comes is `libyara.so.8`. Manually building the libyara following this guide https://yara.readthedocs.io/en/stable/gettingstarted.html generates a `libyara.so.10` and it works fine. 

Does GoReSym actually require the latest features of yara? Could it be built with an earlier version of it so that it runs out of the box on Ubuntu? Or, since yara comes with a quite permissive license (https://github.com/VirusTotal/yara/blob/master/COPYING), could GoReSym statically link with libyara.so.10?

**Comment by stevemk14ebr** [comment]
We use very basic yara features just to do signature scanning, so it's fine to link any version if it's compatible with go-yara. I did attempt to statically link, though if you're seeing issues I guess i've done it wrong:

https://github.com/mandiant/GoReSym/blob/95f27bbcd672d8189e350bee04d44e8fca06cb96/build_all.sh#L22-L23

**Comment by xusheng6** [comment]
> We use very basic yara features just to do signature scanning, so it's fine to link any version if it's compatible with go-yara. I did attempt to statically link, though if you're seeing issues I guess i've done it wrong:
> 
> https://github.com/mandiant/GoReSym/blob/95f27bbcd672d8189e350bee04d44e8fca06cb96/build_all.sh#L22-L23

Yeah, the libyara is not statically linked
