### ISSUE TITLE
macOS build?

### ISSUE THREAD

**Issue by xusheng6** [mandiant/GoReSym#24]
Not sure if this has been discussed before -- is it possible to build GoReSym for macOS?

**Comment by stevemk14ebr** [comment]
I'm sure it is, thought I don't have a mac so I don't support pre-built binaries and cannot provide instructions to do so

**Comment by stevemk14ebr** [comment]
I think I'll explore removing the yara dependency instead to simply the build

**Comment by stevemk14ebr** [comment]
This is resolved with the removal of the yara dependency
