### ISSUE TITLE
Please update with Go 1.18 library

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/GoReSym#4]
pnlntab in Go 1.18 binaries diffence with Go 1.16

**Comment by stevemk14ebr** [comment]
go 1.18 binaries should already be supported, if you're reporting a bug please provide more information

**Comment by stevemk14ebr** [comment]
Closing. With the fixes from https://github.com/mandiant/GoReSym/issues/3 1.18 symbols should be correctly parsed, and their VAs are now correct too.
