### ISSUE TITLE
 Error : Failed to parse file: failed to read pclntab: failed to locate pclntab

### ISSUE THREAD

**Issue by Zorkai** [mandiant/GoReSym#43]
I am trying to use GoReSym on this binary : 
https://mega.nz/file/CqoRQDaS#VDQ6bScWEHLdb1AtkMscdXsZhZWDZNDZWhBvEJ82ZsQ

I doubt this binary is obfuscated.

However, I am getting the following error :

![image](https://github.com/mandiant/GoReSym/assets/48529989/e11b6908-304c-4d6f-b253-1c9fb8781887)

**Comment by stevemk14ebr** [comment]
This is not a go binary. It's a nodejs / chrome binary with javascript inside

https://binmasterdocs.gitbook.io/binmaster-docs/overview/what-is-binmaster

https://github.com/binmasterdotpro/BinMaster-Src/tree/main

**Comment by Zorkai** [comment]
This is actually a go binary, as you can see on the bottom of the repository you sent, it isn't the actual source code but it was a joke for april fools. The repository does not contain any code but only blank files.
![image](https://github.com/mandiant/GoReSym/assets/48529989/14fde74e-c478-42d2-9731-61300fe14df1)

**Comment by stevemk14ebr** [comment]
I can promise you it is not a binary written in the language Golang. I opened it and looked. The file you sent is a node.js binary which embeds chrome. If you think I'm wrong, please prove otherwise.
