### ISSUE TITLE
PCLNTAB - Not all function names present

### ISSUE THREAD

**Issue by bigpie1234** [mandiant/GoReSym#48]
Issue: Not all of the function names are present in a stripped binary's pclntab.

Question: Does pclntab hold ALL of the function names? What is the constraint as to what function names it holds and doesn't hold? When the binary gets stripped, what function names are taken out of pclntab?

**Comment by stevemk14ebr** [comment]
Please share a binary. What specifically is contained within the pclntab can be modified, generally yes it will contain all the function names.
