### ISSUE TITLE
Include license and copyright in the built binaries

### ISSUE THREAD

**Issue by pombredanne** [mandiant/GoReSym#52]
The MIT license is easy to comply with but the current builds make it hard.
It would be awesome to include the MIT license and your copyright in the built binaries, and displaying it in some command line flag with some URL to the project.

This would make compliance automatic and baked in the build.

**Comment by stevemk14ebr** [comment]
Thanks! I've added a flag to print this information to make it easier to comply: https://github.com/mandiant/GoReSym/releases/tag/v2.7.3

**Comment by pombredanne** [comment]
@stevemk14ebr You rock and are awesome! thank you ++
FYI, we integrate GoReSym in https://github.com/nexB/go-inspector/ which will then be used to analyze go binaries to sources in https://nlnet.nl/project/Back2source/ in https://github.com/nexB/scancode.io/

**Comment by stevemk14ebr** [comment]
awesome!
