### ISSUE TITLE
Linux OOM

### ISSUE THREAD

**Issue by pombredanne** [mandiant/GoReSym#61]
GoReSym cli gets proc killed consuming 64GB of RAM on a fast modern laptop running Linux (Ubuntu 22.04) with this  tidb-server (large) Go binary found in a docker image, built from these sources: https://github.com/pingcap/tidb
To get the pre-built binary using docker CLI:
```
docker pull pingcap/tidb@sha256:375160102a038d452e6468321ac02cd58d8fdf1edf8890b942fded5488a12c1b
docker save pingcap/tidb@sha256:375160102a038d452e6468321ac02cd58d8fdf1edf8890b942fded5488a12c1b >pingcap.tar

tar -xf pingcap.tar 
tar -xf a5d7053833d52f85d8f0be1156633cd75e32cd54a630c452cd24dc4a096d5f4f/layer.tar 
ls -al tidb-server 
-rwxr-xr-x 1 pombreda pombreda 228929528 Aug  2 14:04 tidb-server
```

**Comment by stevemk14ebr** [comment]
We implement section caching logic to re-merge sections for more accurate scanning, there are definetely issues in some cases. I'd appreciate if the specific bug could be located

**Comment by pombredanne** [comment]
> We implement section caching logic to re-merge sections for more accurate scanning, there are definetely issues in some cases. I'd appreciate if the specific bug could be located

I am not sure where to look first and where to instruments to catch things. A difficulty is that using the binary mentioned means that in a matter of a few seconds the laptop freezes running out of RAM until it eventually get proc killed by the kernel. There is little to observe in that short time.

Can you tell me where in the code is the caching taking place?

**Comment by stevemk14ebr** [comment]
Here is one cache https://github.com/mandiant/GoReSym/blob/d7d9a98b02b95c2822d59994f632b1f76c4f4266/objfile/objfile.go#L227

Each file type is going to also have a `DataAfterSection` function such as https://github.com/mandiant/GoReSym/blob/d7d9a98b02b95c2822d59994f632b1f76c4f4266/objfile/pe.go#L179 which merged adjacent section data.

These two operations together are where I bet the issues arise

**Comment by mazza-av** [comment]
Also experiencing this no matter what flags are specified

**Comment by stevemk14ebr** [comment]
Can you send your binary so I can see what blows up? There's no built in limit but with the in memory caches we have some binaries explode memory usage with certain layouts or assembly patterns.

**Comment by stevemk14ebr** [comment]
That's a lot of sections. I bet our section caching is what's blowing up https://github.com/mandiant/GoReSym/blob/d7d9a98b02b95c2822d59994f632b1f76c4f4266/objfile/pe.go#L179

**Comment by stevemk14ebr** [comment]
This is helpful, this section caching was originally an optimization. I'm learning through this issue and others we might need to remove it entirely and fall back to redoing operations more slowly. Breaking the tool entirely is a horrible trade-off I'm not willing to make for the sake of some speed.

**Comment by stevemk14ebr** [comment]
Ah, so the pclntab raw data copy for each candidate is way too much. I bet this can be changed to not build the whole candidate array at once and instead send them via a channel like a generator function instead. That way they're at least not all held in memory at the same time.

**Comment by stevemk14ebr** [comment]
@mazza-av can you try out https://github.com/mandiant/GoReSym/commit/54a6712945cd980dcf720c162c1347e14f078155 I've switched to streaming the candidates via go channels (like a generator function). This should significantly reduce the memory pressure.

**Comment by stevemk14ebr** [comment]
From my tests this helped a ton with the OP tidb-server. Memory usage is now "only" ~23GB though processing takes 1-2 minutes. For such a huge binary I think this is much more acceptable than 64GB+ and crashing.

**Comment by stevemk14ebr** [comment]
Out of curiosity of you profile it while you run it on your binary what dominates the runtime. Is there anything that stands out in particular?
